### ISSUE TITLE
Use Travis 

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#116]
Travis CI is really easy to set. I think Iceberg would benefit to use it. 

Before including a Travis support I would like to know if you would like to have a Travis support? @npasserini 

If you want it I can do a PR with the configurations.

**Comment by npasserini** [comment]
Yes of course, travis support is in my backlog... but I postponed it a few
times. So if you want to help you are very welcomed!

**Comment by jecisc** [comment]
I will do it this week-end or maybe at esug :)

**Comment by npasserini** [comment]
@jecisc I've merged this and added the repo to my travis account, and is already "building", but I am not sure if it did run my tests. Do you know how to look at it?

The build is here: https://travis-ci.org/npasserini/iceberg/jobs/156820544

**Comment by npasserini** [comment]
I correct myself, it is clear that the tests have not been run... because they would not run in travis until I change some things. So, I change my questios: do you know how to tell the CI which tests should be run?

**Comment by jecisc** [comment]
By default Travis *should* run all the tests brought by the configuration (only the one brought by the configuration and not by the dependencies).

But you have the possibility to charge that behavior with the smalltalk.ston file.  
See documentation at: https://github.com/hpi-swa/smalltalkCI#testcase-selection
