### ISSUE TITLE
Import Local Repository dialog is not dark theme friendly

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#123]
I don't know if it is a Spec or a Iceberg issue but the dialogs are not Dark Theme friendly: https://puu.sh/qQsaV/a916cef957.png

**Comment by tinchodias** [comment]
It's Spec, I have the same issue with LabelModel in my project.

**Comment by jecisc** [comment]
If this is spec we should open an issue on fogbugs. :)

**Comment by npasserini** [comment]
In fact this is a spec issue, please report it in fogbuz
