### ISSUE TITLE
Add package with Iceberg tool does not work

### ISSUE THREAD

**Issue by SergeStinckwich** [npasserini/iceberg#124]
I try to move one my software from Monticello repo to a git repo and it doesn't work.

For example : 
```
git clone git@github.com:SergeStinckwich/Actalk.git
```
Then add the local repo with the Iceberg tool then load Actalk from CatalogBrowser and try to add the ConfigurationOfActalk or Actalk packages to the repo give the following error.

<img width="843" alt="screen shot 2016-08-28 at 16 03 51" src="https://cloud.githubusercontent.com/assets/327334/18034272/0a64d7a8-6d39-11e6-9003-2d145ecac0b8.png">

**Comment by SergeStinckwich** [comment]
I was able to move my project from Monticello to git by using gitfiletree and after I was able to open the repo with the Iceberg tool.

**Comment by npasserini** [comment]
Hi @SergeStinckwich I am not being able to reproduce this, could you give me some hint?

I even tried to migrate your code myself, and it was successful (look at https://github.com/npasserini/Actalk).

The only thing I found is that Iceberg can't cope nicely with a new repository, when it has not even a single commit (which I registered as #127), but the error message is different... so your problem might still be there, but I can't reproduce it.

**Comment by SergeStinckwich** [comment]
Hum. You start with an empty repo ? I will try to reproduce it.

**Comment by npasserini** [comment]
In fact, starting with an empty repo didn't work (see #127) but after an initial commit with an empty readme file, everything worked. How did you create your repository?

**Comment by npasserini** [comment]
Hi @SergeStinckwich, @demarey has helped me reproduce the bug. I think that the problem is that you are using an old version (it is my fault, because I didn't update the "stable" version). 

So if you know run "Iceberg update" you should be able to commit your packages without problems. Please let me know if you still can't.

**Comment by SergeStinckwich** [comment]
Ok, I switch to another repository, because I used gitfiletree to populate the Actalk one.

Another experiment after doing an Iceberg update. I'm cloning an existing repo with : 
git clone git@github.com:SergeStinckwich/libUrbi.st.git
that contains files but no Pharo packages
and try to add this repo as a local repo, I have now 

<img width="553" alt="screen shot 2016-09-02 at 17 34 22" src="https://cloud.githubusercontent.com/assets/327334/18209307/80cc4982-7133-11e6-9efc-37474e197a7c.png">

**Comment by demarey** [comment]
@ SergeStinckwich Maybe it is because your git project contains a dot in it: libUrbi.st. If it is that, it should not be hard to fix.
