### ISSUE TITLE
Can't handle empty repositories.

### ISSUE THREAD

**Issue by npasserini** [npasserini/iceberg#127]
When importing an empty repository, git branch command returns an empty array, and an error is raised because our gitfiletree backend is not able to recognize the current branch.

Yet the repo has a current branch, it is not reported by the "git branch" command, so we should provide another implementation. (And tests.)

**Comment by npasserini** [comment]
I think this is kind of a bug in git, a repo without commits does not behave very well. But we should be able to cope with it.

**Comment by ThierryGoubier** [comment]
I think GitFileTree avoids that by forcing, at minima, a commit with the repository properties if there is none inside the repository yet.

But I suspect this is weak (if the repository is dirty with a .filetree, then it probably fails). This would give a path to solve that.

**Comment by npasserini** [comment]
Now the libgit backend has a special status with an "unborn" branch, which resembles what libgit does. It does not seem to be necessary for the gitfiletree backend, but maybe we should do the same, for consistency.
