### ISSUE TITLE
User repository

### ISSUE THREAD

**Issue by sbragagnolo** [npasserini/iceberg#137]
Usually, in my machine, i have a folder with all my git projects on it.

I think it would be nice to provide this directory to Iceberg, for checking on this directory for each project or related project to be loaded. 
Like this I can have only one working copy for all my images, and drop the changes always on the same place.

**Comment by dalehenrich** [comment]
@sbragagnolo I think this is a very good idea ... having a well-known location for git projects means that non-code artefacts can be easily accessed by code running in an image ...

**Comment by jecisc** [comment]
I think this is important for the usability of Iceberg.

**Comment by npasserini** [comment]
Hey, I am finally getting to this. Do you have any proposals for a default location for that directory?

**Comment by jecisc** [comment]
Maybe this should be asked on the ML.

Maybe at ` StartupPreferencesLoader preferencesGeneralFolder`?

**Comment by npasserini** [comment]
Added a setting: 

![image](https://cloud.githubusercontent.com/assets/4633913/19932571/df62f40c-a110-11e6-93c4-fb608cb36b9f.png)

**Comment by dalehenrich** [comment]
@npasserini I was kinda thinking that having a **FileLocator** alias would be pretty convenient ... if you had something like `FileLocator sharedGitRepos` and `FileLocator imageGitRepos` that tied into your settings and had reasonable defaults, then you'd be golden ... I'd think
