### ISSUE TITLE
Dropdown menu shows wrong key bindings

### ISSUE THREAD

**Issue by tesonep** [npasserini/iceberg#1409]
![image](https://user-images.githubusercontent.com/355455/107504522-b96d8f00-6b9b-11eb-8e1f-695e62bdb16c.png)

**Comment by tinchodias** [comment]
A couple of weeks ago I debugged it I was puzzled... it looked as something to fix in how the key bindings are printed. 

The shortcut works (despite how it's printed), so I postponed the fix.

**Comment by tinchodias** [comment]
Look at the example of the "Commit" command. The method `IceTipCommitCommand>>#shortcutKey` is:

```smalltalk
shortcutKey
	^ $s meta
```

if you change it to:

```smalltalk
shortcutKey
	^ $s command mac | $s control win | $s control unix
```

then it works.

(Took the idea from the overrides of SpToolCommand class>>#defaultShortcutKey)
