### ISSUE TITLE
Icon not found when right click on a tag in the repository

### ISSUE THREAD

**Issue by guillep** [npasserini/iceberg#1414]
There is seemingly a missing icon

**Comment by tinchodias** [comment]
I need more details. Couldn't reproduce with these steps: I added Iceberg as a repository, I selected it and pressed cmd+r to open the browser (the one that I think you are talking about), expanded "Tags" in the tree on the left side, then right clicked and a context menu appeared.

**Comment by guillep** [comment]
I just reproduced it again in a new pharo9 image.
I imported a pharo repo, went to the repository view, expanded a tag, right clicked on a tag.

![image](https://user-images.githubusercontent.com/708322/107792391-62abb500-6d55-11eb-9fc9-a672840620bf.png)
