### ISSUE TITLE
Cannot select / copy text from the commit description in the repository view

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1415]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/432549/107759244-4f362500-6d28-11eb-88f6-0be67a633142.png">

**Comment by samakhov** [comment]
Hi,
I am investigating this issue. 
**The problem**: The spec element used to display commit info (for label and value) is `SpLabelPresenter`. It seems this one doesn't allow selecting nor copying.

**Approach**: It looks like we need to implement a kind of `IceTipReadOnlyTextMorph`. (But I am not sure the use of Morph is in the plan :thinking: of Iceberg)
![ex_ice](https://user-images.githubusercontent.com/13077011/109432457-99e3bc80-7a0b-11eb-951c-9b7094c72933.png)

And with the use of spec2, I don't know if there is an already existing command or something like that for enabling copying. I checked, I didn't find a Presenter for displaying texts with a copying option.

So maybe a clue on how to implement something like `IceTipReadOnlyTextMorph` with Spec2!!!

**Comment by tinchodias** [comment]
Hello @samakhov, thanks for contributing. Lastly, we tried to remove the direct uses of Morphs (not finished yet, some remaining). In that sense, I think it is more convenient to fix this issue in the direction of the PR of @tesonep (it's a pity that there was an overlap of efforts, I think he started to work on Friday on it).
