### ISSUE TITLE
Experimental Feature Warning should be a Dialog

### ISSUE THREAD

**Issue by tesonep** [npasserini/iceberg#1450]

**Comment by tinchodias** [comment]
What warnings?

**Comment by tesonep** [comment]
When you have changes in the image and you want to pull changes

**Comment by tinchodias** [comment]
Ah, yes, that was terrible.
BTW, this week I had an issue with that feature... I will report it in an issue.

**Comment by tinchodias** [comment]
https://github.com/pharo-vcs/iceberg/issues/1456
