### ISSUE TITLE
IceProxyMCVersionInfo>>#gtDisplayString should be removed

### ISSUE THREAD

**Issue by MarcusDenker** [npasserini/iceberg#1468]
gtDisplayString has no senders anymore and has a deprecation rewrite on the level of Object 

--> it can be removed

**Comment by tinchodias** [comment]
I was going to only push a commit removing this method but after browsing the code of that class, I preferred to comment other removal candidates in the same class:

- gtDisplayOn:
- asSpotterCandidateLink
 
Should we just remove them or there are candidate names for renaming? I mean, for the new inspector / new spotter.

**Comment by Ducasse** [comment]
Martin normally I migrated all the gtDisplayOn: to displayStringOn: 
I should remove all the gtDisplay:.
there should be no reference to gtDisplayOn: (in my PR there were none). Now may be spec got merged and some of my changes got reverted. I do not know.
