### ISSUE TITLE
Error on "Install this version"

### ISSUE THREAD

**Issue by tinchodias** [npasserini/iceberg#1469]
- open Calypso
- select a method that has changes in an iceberg repository
- click on "versions" to open the browser
- select one, right click and "Install this version".
- Get DNU in IceTipInstallVersionCommand>>#version

This is an error introduced by my migration, surely... in Spec2/Commander2, the `context` of a command is a presenter. 

I'm on the fix.

**Comment by VincentBlondeau** [comment]
Can be reproduced:
![image](https://user-images.githubusercontent.com/4706329/116117503-9a6f9b00-a6bc-11eb-86ff-be38b683f881.png)

**Comment by tesonep** [comment]
It has been fixed
