### ISSUE TITLE
When I push I get the ..PushBrowser dNU updateTitle

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1476]
Hi

I pushed some changes to my fork and I got a DNU..PushBrowser dNU updateTitle

**Comment by Ducasse** [comment]
Pharo 9.0.0
Build information: Pharo-9.0.0+build.1332.sha.730e4b90e4702cb039de7ae18c861e017f9ee07b (64 Bit)

**Comment by tesonep** [comment]
It has been fixed
