### ISSUE TITLE
IceCritiquesVisitor does not allow committing

### ISSUE THREAD

**Issue by pavel-krivanek** [npasserini/iceberg#1549]
The lack of existence of `IceCritiquesVisitor >> visitExtensionDefinition:` does prevent to commit changes that involve extension methods to another packages even if the option "Run Critiques when commiting" is not checked

in: vanilla Pharo 10.0.0
Build information: Pharo-10.0.0+build.259.sha.7a92ab64c6593b31b9236a73f736d9971ac87c49 (64 Bit)

![Pharo_bdu7tBeFXM](https://user-images.githubusercontent.com/572494/141997404-d64fa267-fede-46eb-af40-11ccf3221fac.png)

**Comment by vitormcruz** [comment]
@tesonep I am having the same problem while using the latest version dev-2.0, there is some version where this issue was fixed?
