### ISSUE TITLE
DNU: modalRelativeTo: for Iceberg in Pharo9

### ISSUE THREAD

**Issue by astares** [npasserini/iceberg#1555]
I load Seaside (using an own fork) in Pharo 9 image on Linux. While doing this the SSH dialog is popping up
giving a DNU:

![image](https://user-images.githubusercontent.com/5980033/145164328-6e9f70b4-df6f-4e40-a09c-5c505ecea16a.png)

**Comment by MarcusDenker** [comment]
This is fixed: no sender of modalRelativeTo:  anymore
