### ISSUE TITLE
Browsing a repository throws DNU versionFor:

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#156]
Iceberg throws a DNU when we select a repository. IceRepository>>doesNotUnderstand: versionFor:

To reproduce:
- take a fresh pharo 6 image
- evaluate 

``` Smalltalk
Metacello new 
    repository: 'github://demarey/cargo/repository';
    baseline: 'Cargo';
    load: 'tests'.

Metacello new
  baseline: 'Iceberg';
  repository: 'github://npasserini/iceberg:master';
  load.
```
- then run Iceberg and add a repository (clone git@github.com:demarey/cargo with subdirectory repository).
- you will see a red box with the error in the package view

**Comment by estebanlm** [comment]
I think is not there anymore (I cannot reproduce it)
