### ISSUE TITLE
I get a DNU when I checkout master branch on microdown remote

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1561]
![Capture 2022-01-15 at 11 05 53](https://user-images.githubusercontent.com/432549/149617957-711a875a-f35a-4f24-9967-8b3c2dc06919.png)

**Comment by Ducasse** [comment]
aMCPacther is a MCPackageLoader
may be this is because there are some script (.st) in MD repo

**Comment by MarcusDenker** [comment]
same as https://github.com/pharo-vcs/iceberg/issues/1528

**Comment by MarcusDenker** [comment]
fix was merged: https://github.com/pharo-vcs/iceberg/pull/1572
