### ISSUE TITLE
[Pharo9] commit message is not encoded as UTF8

### ISSUE THREAD

**Issue by mumez** [npasserini/iceberg#1562]
Please see the description.
https://github.com/pharo-project/pharo/issues/10781

I tested the issue only on Pharo 9.
Perhaps I can make a pull request if I'm sure which Iceberg version is pre-loaded for Pharo 9.

**Comment by Ducasse** [comment]
Thanks a lot! We will let you know. Indeed a PR is welcome :)
@tesonep ?

**Comment by tinchodias** [comment]
Seems related to #1426

**Comment by MarcusDenker** [comment]
Another issue tracker entry for this, with a proposed solution:

https://github.com/pharo-project/pharo/issues/11226

**Comment by MarcusDenker** [comment]
PR merged in Pharo11 to fix this: https://github.com/pharo-project/pharo/pull/11239
