### ISSUE TITLE
Split GUI from Git model

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#157]
UI code sould be packaged in a dedicated package to allox the use of Git in headless mode

**Comment by npasserini** [comment]
In https://github.com/npasserini/iceberg/commit/7ca1d520dcf5ad57fb65d7135c9aff127171432e I have separated the GUI into an independent package. 

But, so far I understand, Iceberg has been always been able to run in headless mode, or at least travis does run Iceberg tests in headless mode. So, I do not know how to validate that your problem is solved.

**Comment by demarey** [comment]
The use case is to use iceberg from a bootstraped pharo image without UI.
You could try to run iceberg tests from this image: https://ci.inria.fr/pharo/view/6.0-SysConf/job/Pharo-6.0-Step-07-01-ConfigurationOfUnifiedFFI/

**Comment by npasserini** [comment]
I tried that and I get this error:

```
Metaclass(Object)>>doesNotUnderstand: #innerBindingOf:
	Receiver: Callback class
	Arguments and temporary variables: 
		aMessage: 	innerBindingOf: #FlushThunkToCallbackMap
		exception: 	MessageNotUnderstood: Metaclass>>innerBindingOf:
		resumeValue: 	nil
	Receiver's instance variables: 
		superclass: 	Object class
		methodDict: 	a MethodDictionary(#signature:block:->Callback class>>#signature:bl...etc...
		format: 	65551
		layout: 	a FixedLayout
		instanceVariables: 	nil
		organization: 	nil
		thisClass: 	Callback
		traitComposition: 	nil
		localSelectors: 	nil
```

Any ideas?

But still, I am not sure, is this test better than what is done by travis CI? Doesn't travis run in headless mode?

**Comment by demarey** [comment]
Could be an issue from the bootstrapped image.
Travis runs a standard pharo image in headless mode. This image is build from scratch from pharo sources and does not have any UI class loaded. This way you can spot easily any undesired dependency on UI stuff.
Do not spend more time on that. I will notice you if there is more things to split.

**Comment by npasserini** [comment]
Solved in https://github.com/npasserini/iceberg/tree/repackaging
