### ISSUE TITLE
revert repository sorting

### ISSUE THREAD

**Issue by estebanlm** [npasserini/iceberg#1580]
I am hating this change: 
https://github.com/pharo-vcs/iceberg/commit/a28f9ee83aead0bb39a57982795585cfd90375b5

The problem is that an automatic sorting actually changes the position of repositories all the time, making hard to get the "muscular memory" and the mind map the brain makes with the list. 
In consequence, instead being a help, this sorting is very annoying.
Can we revert it please?

**Comment by Ducasse** [comment]
may be we can have a button to sort?

**Comment by akevalion** [comment]
the original issue is: in moose images we have several repositories with status `Local repository missing`
<img width="594" alt="image" src="https://user-images.githubusercontent.com/10532890/160433495-bb09823d-a0f5-4b41-a1da-21e17998e323.png">

And when we modified these repositories, they are at the bottom of the list. Then each time we need to scroll them and we loose time

maybe: 

1. Can we use headers of the table to change the sorting order
2. can we remove or minimize the list of repositories with `Local repository missing`
3. can we save the last sorting criteria, in order to reuse it in a future

**Comment by estebanlm** [comment]
I think you are tackling the problem in a wrong way: 
when you find a repository (one of the possible "repair actions" you have) the repositories are not resorted, they would appear in the original position: 

![image](https://user-images.githubusercontent.com/513630/160590890-c6f0c469-517e-4eb9-80c9-c701ab9354fb.png)

here you can see pharo, Spec and NewTools with correct location... and I know exactly *where* those repositories will appear, always... no need to re-match my mind depending on which image I have loaded, with which projects.

Something tells me that in moose, instead of repair the repositories by setting the local repository, you re-add them :)
This can be fixed easily with a script, and everything will be healthier... 

Still, there is the problem of the organization when you have a lot of repositories. In that case, yes, I can envision several solutions (including the ones you suggested, except the 2... we could hide them with a button but not remove them).
Also: 

1. grouping repositories in meta-projects (and put them in tabs, maybe). I want to do that for pharo, for example.
2. add a "sorting" toolbar with different sorts/filters (including none).
3. as pointed before (but this is a sub-topic of previous suggestion), hide missing repos through a button. 

But none of this can be solved in the context of a freeze for release, and that's why I ask to **revert** and then we can work on a fix that covers all problems.

**Comment by astares** [comment]
@estebanlm maybe that is related to the two models:

 1) the more **Pharo user based** mental model of easier finding own custom repos in a long repo list. This is addressed with the already included change to have an "alphabetical" sort order.  

  => maybe that already fits for the release version 10 which is intended for the end users who based their work on Pharo (like Moose)

 2) the more **Pharo contributor based** mental model (where one knows that Spec  and New Tools might relate and Iceberg and libgit) expecting a specific grouping and specific order as we are used to now 
 
  => maybe that fits better for contributor situation, so should we revert it only for the P11 iteration then, no?

**Comment by akevalion** [comment]
Hello there is a pull request to revert this change https://github.com/pharo-vcs/iceberg/pull/1581

**Comment by estebanlm** [comment]
oups, yours is better ;)

**Comment by MarcusDenker** [comment]
fix was merged
