### ISSUE TITLE
Issue with Critiques and Files

### ISSUE THREAD

**Issue by akevalion** [npasserini/iceberg#1586]
I got this error.

<img width="995" alt="image" src="https://user-images.githubusercontent.com/10532890/167128941-82e3bd96-aee3-4d58-83e4-85e935adb97e.png">

My repository already has a folder with files inside.

Expected result is iceberg should not present critiques for files for the moment.

To solve this issue please add for now

```st 
IceCritiquesVisitor >> #visitDirectoryDefinition: anIceDirectoryDefinition 
"empty method"
```

**Comment by MarcusDenker** [comment]
I did a PR that needs a review
