### ISSUE TITLE
Adding a used trait to a trait with class side method raises an error in Pharo10

### ISSUE THREAD

**Issue by anneetien** [npasserini/iceberg#1608]
1. Take a brand new Pharo 10 image
2. Create two traits 
Trait << #TMyTest1
	package: 'MyPackage1-Exception'
 and 
Trait << #TMyTest2
	package: 'MyPackage-Exception'
in TMyTest2 add a class side method
myMeth
      ^self.
3. Add a new project in Iceberg and add this package.
4. Commit.
Normally here everything goes well.

5. modify the definition of trait TMyTest2
6. Trait << #TMyTest2
        traits: {TMyTest1};
	package: 'MyPackage-Exception'
7. Commit
Normally the error raises here
<img width="996" alt="image" src="https://user-images.githubusercontent.com/17824579/187673612-5a4bb57c-da26-4f5c-924f-e844e437ac85.png">

I don't know if it works in Pharo 11. 
The way you define the trait is important.
The fact that the trait you are modifying already got a class side method is important because adding the used traits has an impact on the trait definition and the class trait definition and it is important that you modify it and not that you add it.

**Comment by anneetien** [comment]
After investigations with Christophe, we modified the following method. It solved the issue, but had a side effect to remove the class trait definition of traits non using other traits.

"protocol: #'private factory'"

newTraitDefinitionFrom: anArray
	| metadata traitDefs |
	
	metadata := anArray sixth.
	traitDefs := { 
		self hasStatefulTraits 
			ifTrue: [ self newStatefulTraitDefinitionFrom: anArray ]
			ifFalse: [ self newStatelessTraitDefinitionFrom: anArray ] }.
			
	"metadata 
		at: #classTraits
		ifPresent: [ :classTraits |"
			traitDefs := traitDefs copyWith: (MCClassTraitDefinition
 				baseTraitName: (metadata at: #name)
 				classTraitComposition: (metadata at: #classTraits ifAbsent: [ '' ])
				category: (metadata at: #category))" ]".
			
	^ traitDefs

**Comment by guillep** [comment]
I confirm I can reproduce the issue

**Comment by guillep** [comment]
I confirm it also happens in Pharo 11
