### ISSUE TITLE
Forget repository Iceberg error on windows

### ISSUE THREAD

**Issue by ELePors** [npasserini/iceberg#1624]
When click on  "Forget repository" in iceberg repository list contextual menu, in pharo 10.0
(Pharo 10.0.0 Build information: Pharo-10.0.0+build.532.sha.d9f862003a88bfc9a17ff12ab7a11abf1fe154a9 (64 Bit))

a Dialog proposes "Are you sure to remove your repository (...) from your image?"
a checkbox proposes to "also remove repository from file system" (which is the most often case... would be checked by default i think).
I check the box... and i click on "Ok"

i get a "CannotDeleteFileException" error... a file created by libGit blocks the deletion of the iceberg sub directory...
Even if i try it manually using my windows explorer.

When i close the Pharo image, the deletion of iceberg directory become possible.

Maybe releasing libGit ressources temporarily is a solution to remove this repository ?

**Comment by Ducasse** [comment]
I do not know. 
But I rarely want to remove my files when I remove a repo.

**Comment by Ducasse** [comment]
So to me the default is good.

**Comment by tesonep** [comment]
Fixed in P11, @ELePors do you need that we backport this fix?

**Comment by ELePors** [comment]
The backport in Pharo 10 or 9 can be useful for community members, but we are on P11… so it is not a priority for us. 

But if it is simple to correct, please do it. 

 

Eric LE PORS

--------

THALES DMS France,

User Experience Lead,

IDE – UX, Brest

Tel : (+33)7 64 36 94 17

 <sip://5080012956,639948/> Jabber conference

 <sip://0298315559/> Appel direct

 

De : Pablo Tesone ***@***.***> 
Envoyé : jeudi 24 novembre 2022 12:22
À : pharo-vcs/iceberg ***@***.***>
Cc : LE PORS Eric ***@***.***>; Mention ***@***.***>
Objet : Re: [pharo-vcs/iceberg] Forget repository Iceberg error on windows (Issue #1624)

 

Fixed in P11, @ELePors <https://github.com/ELePors>  do you need that we backport this fix?
