### ISSUE TITLE
Sort repositories in Iceberg main visualization (IceTipRepositoriesModel)

### ISSUE THREAD

**Issue by NicolasAnquetil** [npasserini/iceberg#1650]
I don't like repository list in Iceberg because there is no order, it is hard to find a repo in there.

when there are three pages of repositories (eg. Moose images), it is hard to find the one you want.

I could resolve it locally with:
```Smalltalk
IceTipRepositoriesModel >> repositories
    ^ (repositoryProvider repositories collect: [ :each | (IceTipRepositoryModel on: each) beCached ])
        sorted: [ :a :b | a name asLowercase < b name asLowercase ]
```

I am not creating a PR beause on a fresh P11 image, I have 48 failing test before the change and 56 after.
8 tests in IceTipRepositoriesBrowserTest fail because they are based on the old order.
I am not sure whether this is a feature or a bug

**Comment by estebanlm** [comment]
Hi,
No, this will not be included, sorry. It breaks the workflow of everybody else and the gain can be easily provided by something else (I already reverted this change once).
Now, I am not saying that there is no need to be able to find better ways to present this data, and in that sense next integration of iceberg will have something like this : 

![image](https://user-images.githubusercontent.com/513630/208691480-0e0e2d3a-c24f-406e-b144-c9666a3b2989.png)

As you see, there are 3 elements there now : 

1. you will be able to group your projects adding a tag to your `.project` metadata. So, you would be able to have `Moose` as a group (or whatever you want), as in the image you see "projects" and "system".
2. column headers on repository and status are now clickable (and sortable)
3. you will have also a filter

I guess this changes will address your problem in a better way than just force a sort.
