### ISSUE TITLE
Open the working directory in a FileList

### ISSUE THREAD

**Issue by privat** [npasserini/iceberg#1662]
Add an icon or menu item somewhere to open a FileList browser in the working directory.

It could then be used to view README files or navigate any other files non managed by iceberg.

**Comment by astares** [comment]
@privat 

That is already available:

![image](https://user-images.githubusercontent.com/5980033/213297483-5ea2d5f4-3211-43f7-bc13-34a909bb5912.png)

**Comment by privat** [comment]
Oh, indeed.

The discoverability of this option could be improved.
