### ISSUE TITLE
Cannot open commit window from repository list anymore

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#1665]
The new version of the UI of Iceberg does not honour anymore the CMD+S shortcut that allows to open the commit windows on the selected repository. It should be added back because very useful.

**Comment by estebanlm** [comment]
lol, it does honor it... is just broken somewhere else ;)

**Comment by demarey** [comment]
When you press CMD +S, the $s character is caught by the table search. Probably, the problem is there.
Also, even with table search disabled, the CMD + S shortcut does not work
