### ISSUE TITLE
Project filter broke the shortcuts

### ISSUE THREAD

**Issue by PalumboN** [npasserini/iceberg#1671]
With the last UI update, shortcuts in the repositories list are impossible to use. It starts to write in the filter instead:

![image](https://user-images.githubusercontent.com/4098184/215468325-7d7ba458-02c0-46a5-b22f-968a79adbde9.png)
(Using `cmd + S` to commit)

Anyway, if you start to write directly with the focus in the list, the filter is filled but doesn't work:

![image](https://user-images.githubusercontent.com/4098184/215468830-5befc132-9f88-42f5-80be-637f8806f1a3.png)

You have to select the filter and then write.

**Comment by jordanmontt** [comment]
Hello, I just tested this and now it works. Can we close this issue? @PalumboN 
Also, this was caused not by iceberg but by a bug that was introduced in a Pharo Sprint when registering the keystroke events.###

**Comment by PalumboN** [comment]
Yes! Now it's working. Cool
