### ISSUE TITLE
self application inform: inherits from Object => UIManager dependency

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1712]
The following is an example. 
So probably that SpApplication should offer inform: 

```
execute 
	| contents |

	contents := self page contents.
	contents ifEmpty: [
		self application inform: 'Nothing was published because the playground is empty'.
		^ self ].

	(IcePublishGistPresenter newApplication: self application)
		content: contents withUnixLineEndings;
		whenPublishedDo: [ :jsonResult |
			self application inform: (jsonResult at: 'html_url') , ' was published and the url was copied to clipboard' ];
		openModal
```

**Comment by Ducasse** [comment]
Let me know because I can introduce inform: in SpApplication

**Comment by estebanlm** [comment]
uhm... I would prefer to replace that for newInform... etc.

**Comment by Ducasse** [comment]
Do you mean 

```
(IcePublishGistPresenter newApplication: self application)
		content: contents withUnixLineEndings;
		whenPublishedDo: [ :jsonResult |
			self application newInform
   title: 'Inform!';
   label: (jsonResult at: 'html_url') , ' was published and the url was copied to clipboard' ];
		openModal

```

**Comment by estebanlm** [comment]
```Smalltalk
self application newInform
    title: 'A title';
    label: 'A message';
    openModal.
```

**Comment by Ducasse** [comment]
Yes this is what I wrote. 
Now I cannot find the code anymore and I loaded the latest version + the tests (development group via the baseline). So may be this code was removed in the meantime. 

But I found many other self inform: in presenters and I was starting to fix them. 
Now I'm basically duplicating 
self application newInform and I was wondering if we could not just define it once on SpPresenter 

```
SpPresenter >> newInform
     ^ self application newInform
```

Tell me what you think

**Comment by Ducasse** [comment]
I added in some presenters for now because this is too boring to do it 8 times in SpChangeSorterPresenter for example.

```
inform: aString

	^ self application newInform 
			title: 'Alert';
			label: aString;
			openModal
```

**Comment by estebanlm** [comment]
> Yes this is what I wrote. Now I cannot find the code anymore and I loaded the latest version + the tests (development group via the baseline). So may be this code was removed in the meantime.
> 
> But I found many other self inform: in presenters and I was starting to fix them. Now I'm basically duplicating self application newInform and I was wondering if we could not just define it once on SpPresenter
> 
> ```
> SpPresenter >> newInform
>      ^ self application newInform
> ```
> 
> Tell me what you think

uhm... maybe?  
the problem is the explosion of methods with all possibilities.  
I would maybe add just the simplest one (`#inform:`), with a comment "for a more complex behavior, see `newInform`..."

**Comment by Ducasse** [comment]
for now I'm doing a pass to remove a first set of dependencies to UIManager and we see. I'm cleaning also the examples

```
exampleModal

	| ok dialog |
	dialog := self new.
	ok := dialog
		title: 'Confirm modal example';
		label: 'Are you sure?';
		acceptLabel: 'Sure!';
		cancelLabel: 'No, forget it';
		openModal.
	
	dialog application newInform
		title: 'Alert';
		label: (ok ifTrue: [ 'Yes!' ] ifFalse: [ 'No!' ]);
		openModal 
```

**Comment by Ducasse** [comment]
Now for other class methods such as 

```
browseVersionsForClass: aClass selector: aSelector
	^ aClass
		compiledMethodAt: aSelector
		ifPresent: [ :method | self browseVersionsForMethod: method ]
		ifAbsent: [ self
				inform:
					('No method {1} in class {2}'
						format:
							{aSelector.
							aClass printString}) ]
```

I cannot use the self application newInform so I will use SpInformDialog but I do not think it is equivalent because of the owner.

**Comment by estebanlm** [comment]
why you can't? `VersionBrowser` is a presenter, it will understand application

**Comment by Ducasse** [comment]
in playground I wrote

```
execute 
	| contents publishedUrl |

	(self application newConfirm
			title: 'Confirm please!'; 
			label: 'Publish playground content to the cloud?';
			openModal) 
		ifFalse: [ ^ self ].
	
	contents := self page contents.
	contents ifEmpty: [ 
        self application newInform 
				title: 'Alert'; 
				label: 'Nothing was published because the playground is empty'; 
				openModal.
        ^ self ].

    Clipboard clipboardText: (publishedUrl := (self post: contents) asString).
   self application newInform 
				title: 'Alert'; 
				label: publishedUrl , ' was published and the url was copied to clipboard';
				openModal
```

And now I think that it would be better to define inform: in SpPresenter as 

```
SpPresenter >> inform: aString
       "Display an inform dialog, for more configurable version please use self application newInform." 

      ^  self application inform: aString

SpApplication >> inform: 
	^ self newInform
	        title: 'Alert'; 
		label: aString; 
                openModal
```

**Comment by Ducasse** [comment]
> why you can't? `VersionBrowser` is a presenter, it will understand application

Because this is on the class side. Is a class side understand application? I tried and it did not work as I expected it.

**Comment by Ducasse** [comment]
I added the helpers 

```
SpPresenter >> inform: aString
	"Displays a simple inform dialog, for more configurable version please use `self application newInform title: ....`."

	^ self application inform: aString
```

```
inform: aString
	"Displays an inform dialog, for more configurable version please use `self application newInform title: ....`."

	^ self newInform
		  title: 'Alert';
		  label: aString;
		  openModal
``` 
and it lets the code shrink. So I will continue. We can inline the methods later if this is a problem.
Tell me what you think.

**Comment by Ducasse** [comment]
This is good because like that I do not have to rewrite all the inform: calls and they are many of them.

**Comment by Ducasse** [comment]
I will close this issue because there is https://github.com/pharo-vcs/iceberg/issues/1723
