### ISSUE TITLE
Alert about the method push without instance variables should have two buttons

### ISSUE THREAD

**Issue by pavel-krivanek** [npasserini/iceberg#1721]
Alert dialog about the method push without instance variables should have two buttons - OK and Cancel or Continua and Cancel. In the current state, it asks on a what to do but does not have options.

![iceberg-alert](https://github.com/pharo-vcs/iceberg/assets/572494/913cbfef-1b12-42de-bde3-58619824615f)

**Comment by Ducasse** [comment]
We should move this issue to Pharo.

**Comment by Ducasse** [comment]
migrated
