### ISSUE TITLE
Arguments of methods from traits are renamed upon loading

### ISSUE THREAD

**Issue by bouraqadi** [npasserini/iceberg#1768]
Bug found on Pharo 12.

**How to reproduce the bug**

1. Create a repository Demo
2. In Demo add a trait TA that defines method

```
Trait << #TA
	package: 'Demo'

TA >> #m: someObject
	^someObject 
```
3. In the same repository define a class A that uses the trait TA
```
Object << #A
	traits: {TA};
	slots: {};
	package: 'Demo'
```

4. Commit the Demo
5. Remove Demo from the image
6. Load back Demo to the image
7. Bug: Method #m in class `A` is displayed as following
```
A >> #m: arg1

	^ arg1
```

This happens only with Iceberg. Filing out and loading back the .st file saves argument names

**Comment by Ducasse** [comment]
@jecisc do you think that it can be linked to some announcement removal?

**Comment by jecisc** [comment]
Fixed since a few weeks
