### ISSUE TITLE
DNU when repair: Discard Image changes and load repository version

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1787]
![Capture 2023-12-31 at 22 38 36](https://github.com/pharo-vcs/iceberg/assets/432549/e74e4e0a-f981-447e-8639-546b0e1f2523)

**Comment by estebanlm** [comment]
I can't reproduce this. 
Is still present?

**Comment by Ducasse** [comment]
Let us close it I will try to check it.
