### ISSUE TITLE
Create tag does not look to create a tag

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1801]
On Pharo 11
- I added a new tag
- it does not appear in the list
- It does not appear with git tag 
So may be we got a regression
I did not have the time to check in P12.

**Comment by Ducasse** [comment]
When I do it from the command line I can them see it in the repository tag list.

**Comment by astares** [comment]
Can confirm the issue also for Pharo 11. List does not update.

BTW: some UI tools like TortoiseGIT show the tags directly in the log list, so one can easily see which commit was tagged
Example:
<img width="374" alt="image" src="https://github.com/pharo-vcs/iceberg/assets/5980033/8ae4bf2a-17b1-45d5-8030-e709a0a77bd5">

**Comment by Ducasse** [comment]
Yes this would be useful.

**Comment by astares** [comment]
See also https://github.com/pharo-vcs/iceberg/issues/1037

**Comment by Ducasse** [comment]
I close this one since this is a duplicate.
