### ISSUE TITLE
Red screen of death while attaching repository

### ISSUE THREAD

**Issue by hernanmd** [npasserini/iceberg#1803]
## Description

I cannot attach my own fork of Microdown to Pharo 12 because of Iceberg error.

## How to reproduce

- Clone [this](https://github.com/hernanmd/Microdown) repository into a local directory
- Open latest Pharo 12
- Open Iceberg -> System -> Microdown -> Repair
- Select local directory
- Red screen of death in the Repositories window

<img width="1440" alt="Screenshot 2024-01-29 at 15 06 56" src="https://github.com/pillar-markup/Microdown/assets/4825959/00dbacf0-3b90-4895-b62c-3281d2aeb998">

## Details

I did a diff between the two clones but couldn't see any significative so far difference leading to the error:

```bash
g clone git@github.com:pillar-markup/Microdown.git Microdown-upstream
g clone git@github.com:hernanmd/Microdown.git Microdown-hernanmd
diff -uprN Microdown-upstream Microdown-hernanmd > microdown-diffs.txt
```

Here's the output

[microdown-diffs.txt](https://github.com/pharo-vcs/iceberg/files/14232527/microdown-diffs.txt)

The debugger reports: `NotFound: object not found - no match for id (0fa8e29a56914e51dcd9368f44c8f05719295602)`

**Comment by estebanlm** [comment]
is this still a thing,  @hernanmd?

**Comment by hernanmd** [comment]
Just tried and couldn't reproduce anymore, so I'm closing it.
