### ISSUE TITLE
Erros in auth dialog when using https

### ISSUE THREAD

**Issue by guillep** [npasserini/iceberg#1805]
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1390.sha.6cefa1c3d575720237036249a266e167366ab7d9 (64 Bit)

- Use an HTTPS remote with no credentials attached
- attempt a push, this will open the auth popup

# Error 1: close it with Cmd+W or cancel (after filling the fields)

<img width="1148" alt="imagen" src="https://github.com/pharo-vcs/iceberg/assets/708322/0dd270e5-af4e-4dd3-a03a-73d25b2acce2">

# Error 2: click on ok with empty user or pass

<img width="844" alt="imagen" src="https://github.com/pharo-vcs/iceberg/assets/708322/6a998f2d-813d-40af-a66b-f768dda42bc3">

We have an untrapped exception.

**Comment by estebanlm** [comment]
error 1: it was a problem of strict mode that is already fixed.
