### ISSUE TITLE
Error on browse method versions

### ISSUE THREAD

**Issue by tinchodias** [npasserini/iceberg#1811]
To reproduce, in P12 browse a method with associated Iceberg repository, and click on "Versions" to get the error.

We must fix this method: https://github.com/pharo-vcs/libgit2-pharo-bindings/blob/f030ad88b9dbedaf6b24ee0501e2c828b55bb0e9/LibGit-Core.package/LGitTree.class/instance/pathspec_match.flags..st#L3

The cause is P12's strict mode ON (the new default).

This is the C function: https://libgit2.org/libgit2/#HEAD/group/pathspec/git_pathspec_match_tree
The parameter type is "git_pathspec_match_list **"... I didn't find a fix for now.

**Comment by tinchodias** [comment]
I think https://github.com/pharo-vcs/libgit2-pharo-bindings/pull/81 fixes it for both P11 and P12

**Comment by estebanlm** [comment]
this is fixed in latest version
