### ISSUE TITLE
Setting global properties raise a DNU

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1828]
- if this is the first time that you use Git in your account
- you get a DNU because the model is nil

**Comment by skycluster** [comment]
Is there some sort of a workaround to get this working for now?
Happening on a clean Pharo 12.0 stable.
<img width="973" alt="Screenshot 2024-07-20 at 00 42 51" src="https://github.com/user-attachments/assets/ae020d14-2f79-4146-9eb8-79c110ded716">

**Comment by skycluster** [comment]
I got it to work with manually applying
```
git config user.email "you@example.com"
git config user.name "Your Name"
```
from the OS command line. The git file structure is there no matter the exception...

**Comment by Ducasse** [comment]
Thanks a lot for your bug report. We are sorry for the inconvenience. We already encountered and it is on our endless todo now since it happens only the first time we always have more urgent bug to fix.

**Comment by Ducasse** [comment]
Same as #1820

**Comment by Ducasse** [comment]
https://github.com/pharo-project/pharo/issues/16979

**Comment by guillep** [comment]
Fixed in Pharo 12, we must forward port it to P13
