### ISSUE TITLE
Push window does not honor selected remote

### ISSUE THREAD

**Issue by guillep** [npasserini/iceberg#1831]
I click on push, the window is opened with a default remote selected (which is ok to me, I want to push there)

<img width="603" alt="imagen" src="https://github.com/pharo-vcs/iceberg/assets/708322/5ae62769-6996-4150-8639-15903f759f53">

I click on Push, and!

<img width="491" alt="imagen" src="https://github.com/pharo-vcs/iceberg/assets/708322/c8291be6-c85e-4f55-a722-43dcba577f33">

I have a permission denied. Of course, It tried to push to another remote and not the one selected!

Moreover, if I change remote (select the second remote, then select back the first one in the list), everything is ok.

Finally, the list of commits shown to push are not the ones to push to the selected remote but to the other one!

It's like the shown remote is not the selected remote.

**Comment by Ducasse** [comment]
This is the same bug we faced with Quentin Moutté

**Comment by guillep** [comment]
I chased this down a bit.

The problem is that inside the drop down, the dropdown items are all *equal* (they respond `true` to `=`) systematically.
This seems to happen because the drop list items have not their display block set, so they return an `asString` of the model.

This means there are two issues:
 - how comes the drop down shows a description if the display block is not set???
 - selection never works by default if the prinstring is not correctly set. We should probably use identity comparisons?

**Comment by guillep** [comment]
The answer to the first question is that it is the droplist that has the display block

```smalltalk
initializePresenters

	remoteList := self newDropList
		display: [ :each | each shortDescription ];
		yourself.
...
```

So, is the display block in the item required/useful?

**Comment by guillep** [comment]
Fixed in P12 and P13 in Spec
