### ISSUE TITLE
iceberg fails to display information on a local repository

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#185]
I created a local repository in Iceberg. The code was already loaded in the image with Metacello (github repo).
When I click on the newly created repository, I get a red morph.
The problem is that Iceberg cannot get information on the current version of packages in the image because the local repository is one version below than the current version loaded.
Maybe Iceberg should do a fetch on the local repo to get latest versions before trying to get the version.

**Comment by npasserini** [comment]
As of https://github.com/npasserini/iceberg/commit/1b4d870ef948137cf0eecda45a53e52168ebe3a2 does not seem to fail, added test testImportOutdatedLocalRepository
