### ISSUE TITLE
Comment pane should be prefilled with information such as 

### ISSUE THREAD

**Issue by Ducasse** [npasserini/iceberg#1852]
Fix: # 
as shown in the screenshot
We could even put the branch name or a link directly to the issue

![Capture 2024-11-12 at 20 58 54](https://github.com/user-attachments/assets/8bad866c-ff3a-4070-bc1a-ff7caff5f56d)

**Comment by AlexisCnockaert** [comment]
![Screen Shot 2024-11-13 at 10 56 42](https://github.com/user-attachments/assets/ba88bbb3-2925-4eb2-bad4-8ce59744dc7f)

would this look good ?

**Comment by AlexisCnockaert** [comment]
Fixes # 1852
