### ISSUE TITLE
Iceberg fails to compute reference commit

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#186]
I loaded my project into image A, did some work, committed/push, do some other work. I use a local git repository.
Then I loaded my project into image B, using the same local git repository, did some work, commited/push, did some work, commited/push.
When I go back to image A, I cannot see the list of new commits to pull in. In the synchronize view, I clicked on _fetch new versions_ and I got the following error:
**ShouldBeImplemented: #computeReferenceCommit should have been implemented in IceLoadedCode**
Indeed, we reach the last step: _"4. We could try other strategies... but this should be good for now."_. Looks like it is not enough or there was a problem before.

**Comment by estebanlm** [comment]
ok, this is done (at least, there is an `IceLoadedCode>>#computeReferenceCommit` ;)
