### ISSUE TITLE
New branch dialog: Pressing enter should activate the ok action

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#1867]
When creating a new branch I often use the view to create a new branch by name and each time I end up wanting to press enter to validate but it does not validate the dialog. I think it should be done to improve the UX.

@AlexisCnockaert I'm not sure what is the best solution for this but maybe you can ask to Esteban?

![image](https://github.com/user-attachments/assets/2b3449be-145f-4da2-b682-7a11b502cd1c)

**Comment by AlexisCnockaert** [comment]
@estebanlm I was thinking to use the whenSubmitDo: method because other presenters already use this to trigger the ok action when pressing enter, what do you think ?
