### ISSUE TITLE
MessageNotUnderstood: ExternalAddress>>newFile

### ISSUE THREAD

**Issue by npasserini** [npasserini/iceberg#213]
Hi @npasserini , @girba told me to make a try with the dev-0.4 to know if it fixes some issues we face (see the screenshot).
screen shot 2016-11-22 at 3 35 01 pm

I tried it and i faced a new issue related to this commit e439723.

MessageNotUnderstood: ExternalAddress>>newFile
in LGitDiff>>includesFileNamed:
I make a comment here to highlight this commit but i can open an issue if you find it more relevant.

**Comment by npasserini** [comment]
@GlennCavarle Please try again.

**Comment by GlennCavarle** [comment]
Thanks @npasserini, loading with the dev-0.4 is working now.
