### ISSUE TITLE
Error while to synchronize a repository

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#244]
OS: Windows 7
Pharo: 6
VM: CoInterpreter * VMMaker.oscog-rsf.2072 uuid: a71106f7-964a-4165-bd14-cd8b52ca1acf Jan  5 2017
StackToRegisterMappingCogit * VMMaker.oscog-rsf.2072 uuid: a71106f7-964a-4165-bd14-cd8b52ca1acf Jan  5 2017
VM: 201701050810 https://github.com/pharo-project/pharo-vm.git $ Date: Thu Jan 5 09:10:34 2017 +0100 $ Plugins: 201701050810 https://github.com/pharo-project/pharo-vm.git $

How I loaded Iceberg:

    Metacello new
	    baseline: 'Iceberg';
	    repository: 'github://npasserini/iceberg:multi-remotes';
	    load.
    #IceRepository asClass defaultBackendType: #IceLibgitLocalRepository.

What happened:

I cloned a new repository.
I did a right click then selected "Synchronize repository"
I got this: https://puu.sh/tdmxe/4059900abe.png

```
ExternalAddress(Object)>>primitiveFailed:
ExternalAddress(Object)>>primitiveFailed
ExternalAddress(ByteArray)>>integerAt:size:signed:
ExternalAddress(ByteArray)>>unsignedByteAt:
ExternalAddress(ByteArray)>>unsignedCharAt:
ExternalData>>fromCString
ExternalData>>readString
LGitDiffFile>>path
[ :delta :second :third | 
| modifiedFileName |
modifiedFileName := delta newFile path.
(modifiedFileName beginsWith: path) asAlien ] in LGitDiff>>includesFileNamed: in Block: [ :delta :second :third | ...
[ :deltaAddress :progress :payload | 
aThreeArgBlock
	value: (LGitDiffDelta fromHandle: deltaAddress)
	value: progress
	value: payload ] in LGitDiffFileCallback>>wrapBlock: in Block: [ :deltaAddress :progress :payload | ...
LGitDiffFileCallback(FFICallback)>>valueWithContext:sp:
CallbackForIA32(Callback)>>evaluatorValueWithContext:sp:
CallbackForIA32>>valueInContext:
Callback class>>evaluateCallbackForContext:
[ type := Callback evaluateCallbackForContext: callbackAlien ] in Alien class>>invokeCallbackContext: in Block: [ type := Callback evaluateCallbackForContext: cal...etc...
BlockClosure>>ifCurtailed:
Alien class>>invokeCallbackContext:
LGitDiff>>diff_foreach:file_cb:binary_cb:hunk_cb:line_cb:payload:
LGitDiff>>filesDo:binaryFilesDo:hunksDo:linesDo:
LGitDiff>>filesDo:
LGitDiff>>includesFileNamed:
[ selfTree := self tree.
parentTree := parent tree.
diff := (LGitDiff of: self repository)
	diffTree: selfTree
	toTree: parentTree.
diff includesFileNamed: fileName ] in [ :parent | 
| selfTree parentTree diff |
[ selfTree := self tree.
parentTree := parent tree.
diff := (LGitDiff of: self repository)
	diffTree: selfTree
	toTree: parentTree.
diff includesFileNamed: fileName ]
	ensure: [ {diff.
		selfTree.
		parentTree} do: #free ] ] in LGitCommit>>changesFileNamed: in Block: [ selfTree := self tree....
BlockClosure>>ensure:
[ :parent | 
| selfTree parentTree diff |
[ selfTree := self tree.
parentTree := parent tree.
diff := (LGitDiff of: self repository)
	diffTree: selfTree
	toTree: parentTree.
diff includesFileNamed: fileName ]
	ensure: [ {diff.
		selfTree.
		parentTree} do: #free ] ] in LGitCommit>>changesFileNamed: in Block: [ :parent | ...
[ :each | 
(aBlock value: each)
	ifFalse: [ ^ false ] ] in Array(Collection)>>allSatisfy: in Block: [ :each | ...
Array(SequenceableCollection)>>do:
Array(Collection)>>allSatisfy:
LGitCommit>>changesFileNamed:
IceLibgitCommitWalk>>shouldInclude:
[ :result | self shouldInclude: result ] in IceLibgitCommitWalk>>rawResultsDo: in Block: [ :result | self shouldInclude: result ]

```

**Comment by estebanlm** [comment]
do you know which "path" is trying to get? (I mean, what should be the resulting string) and trying to get which byte it fails?

**Comment by jecisc** [comment]
@estebanlm I was trying with another repository to give you the information and now I got a VM crash: 
http://puu.sh/te9B5/34094b7707.png

I have NO crash.dump.

**Comment by estebanlm** [comment]
damn :( 
if you execute PharoConsole.exe (from a console) instead, you will likely have the dump.

**Comment by jecisc** [comment]
@estebanlm I tried again and I got this: http://puu.sh/te9NL/7e85c053a4.png

Is it what you wanted?

**Comment by jecisc** [comment]
I reproduced the VM crash in PharoConsole but still no dump :( This is maybe a right problem. With the new VM I cannot open an image located in ProgramFile (x86) because of write right on the .change. Maybe this is the same problem preventing to write the dump.

But I could open those image and write in the .change at this location with my old spur VM.

**Comment by jecisc** [comment]
@estebanlm Where should I open a bug entry about the right problem? Fogbugz? OpenSmalltalk/opensmalltalk-vm? estebanlm/pharo-vm? pharo-project/pharo-vm?

**Comment by estebanlm** [comment]
so yes, this was what I wanted: `#prim_path` is NULL and `#readString` is trying to convert it to a string anyway.
Mmm... I don't know if I should fix that in UFFI or add a verification in `LGitDiffFile>>path`.

**Comment by estebanlm** [comment]
the other problem is likely a problem with `FilePlugin`, but I don't know. 
You need to report in fogbugz, under `Pharo VM` project... I have a fair amount of issues waiting for me there :(

**Comment by jecisc** [comment]
Yes I am aware of it but since you asked for feedback on Iceberg and the new vm I tried them.
And Iceberg does not work with my old vm. I will open the bug entry.

**Comment by jecisc** [comment]
https://pharo.fogbugz.com/f/cases/19525/No-write-right-on-Windows-with-the-new-VM

**Comment by estebanlm** [comment]
I want/need the feedback. Otherwise we will never stabilise :)

**Comment by estebanlm** [comment]
so well... this will be fixed in next integration of Pharo: https://pharo.fogbugz.com/f/cases/19526 :)
