### ISSUE TITLE
Big repositories take ages to load

### ISSUE THREAD

**Issue by guillep** [npasserini/iceberg#248]
When loading a big repository (e.g., https://github.com/guillep/pharo-core), iceberg takes minutes and minutes just to give back the control to the developer.

This freeze does not happen when the repository is created actually. Actually, executing the following will not freeze:
```
repository := IceRepositoryCreator new 
	remote: (IceRemote url: 'git@github.com:guillep/pharo-core.git' trim);
	location: nil;
	subdirectory: 'src';
	createRepository.
repository register.
```

The freeze does not happen until the UI is open, because it is the UI that tries to access `incomingCommits`, which is a lazily initiazed property from the repository.

To calculate these incoming commits, iceberg iterates the entire history of the repository for each of the packages, making a diff between the actual MC version of each package in the image and the one in the iterated version.

This is of course visible in pharo-core because it has ~500 packages, and thousands of classes and methods.

On the one hand, this makes iceberg not usable to manage pharo sources.
On the other hand, it looks like this implementation may several problems:
 - first, it has a package-oriented view. It tries to assign a version per package and not per repository.
 - second, if the version in the image does not correspond to any version in the repo (because for example we added a method) then it will not match any version in the repository. And this means that it will end up iterating the entire history for nothing.

I think we need a simpler solution for this.
 - either we need to store commit ids for each MCWorkingCopy or so in the image to avoid the revwalk. But for code loaded from monticello this may never be true, and thus may never be correct.
 - either we just assume that code that was in the image and was not loaded from git, or even the ones there before iceberg was loaded cannot be linked ***automagically*** to a git commit. And then we need a strategy to handle this case. To me the simplest is to assume that we work on what was checked out from git, without  iterating the history.

**Comment by guillep** [comment]
This problem is also present when synchronizing the repository. And moreover, I found a problem in the callbacks used for this.

```
AlienWeakTable does not understand copyGrownBy:
```

in AlienWeakTable>>add:finalizing:

**Comment by guillep** [comment]
I'm playing adding a lazy iteration of the revwalk, like this:

```
IceAbstractCommitWalk>>versionsFor: package detect: conditionBlock ifNone: noneBlock 
	
	self modifyingPackage: package.
	
	self commitsDo: [ :commit | | version |
		version := commit versionFor: package.
		(conditionBlock value: version)
			ifTrue: [ ^ version ] ].
		
	^ noneBlock value
```

However, it still takes 30 seconds to just check for the version of a single package.

```
[self
		versionsDetect: [ :version | workingCopyAncestors includes: version info  ] 
		ifNone: [ 
			self workingCopy repositoryGroup repositories do: [ :mcRepo |
				mcRepo commitIdFor: self workingCopy ifFound: [ :commitOrTag | 
					(self repository revparse: commitOrTag) versionFor: self ]
			].
		
			IceForeignVersion forPackage: self.
		]] timeToRun
```

I also noticed that the condition inside the detect looks like always answering false:

`workingCopyAncestors includes: version info`

In the problematic case, where there is code in the image that was not loaded from iceberg, `workingCopyAncestors` is a collection of `MCLazyVersionInfo`. However, the version that arrives to the detect is a `IceMCVersionInfo`. And the uuid for the first one is generated by Monticello, while the second one is generated as a SHA1 from the id of a IceCommitInfo.

Am I wrong?

**Comment by dalehenrich** [comment]
On 1/10/17 6:02 AM, Guillermo wrote:
>
> When loading a big repository (e.g., 
> https://github.com/guillep/pharo-core), iceberg takes minutes and 
> minutes just to give back the control to the developer.
>
> This freeze does not happen when the repository is created actually. 
> Actually, executing the following will not freeze:
>
> |repository := IceRepositoryCreator new remote: (IceRemote url: 
> 'git@github.com:guillep/pharo-core.git' trim); location: nil; 
> subdirectory: 'src'; createRepository. repository register. |
>
> The freeze does not happen until the UI is open, because it is the UI 
> that tries to access |incomingCommits|, which is a lazily initiazed 
> property from the repository.
>
> To calculate these incoming commits, iceberg iterates the entire 
> history of the repository for each of the packages, making a diff 
> between the actual MC version of each package in the image and the one 
> in the iterated version.
>
> This is of course visible in pharo-core because it has ~500 packages, 
> and thousands of classes and methods.
>
> On the one hand, this makes iceberg not usable to manage pharo sources.
> On the other hand, it looks like this implementation may several problems:
>
>   * first, it has a package-oriented view. It tries to assign a
>     version per package and not per repository.
>   * second, if the version in the image does not correspond to any
>     version in the repo (because for example we added a method) then
>     it will not match any version in the repository. And this means
>     that it will end up iterating the entire history for nothing.
>

> I think we need a simpler solution for this.
>
>   * either we need to store commit ids for each MCWorkingCopy or so in
>     the image to avoid the revwalk. But for code loaded from
>     monticello this may never be true, and thus may never be correct.
>   * either we just assume that code that was in the image and was not
>     loaded from git, or even the ones there before iceberg was loaded
>     cannot be linked */automagically/* to a git commit. And then we
>     need a strategy to handle this case. To me the simplest is to
>     assume that we work on what was checked out from git, without
>     iterating the history.
>
I've been advocating a project-centric approach as well ...there is a 1 
to1 mapping between a Metacello project and a git repository that can be 
leveraged ... I think that it takes a bit more tools work to properly 
support a project-centric approach, but for working with git 
repositories it is much more natural and efficient ...

There should be a Metacello project browser-like window that replaces 
the Monticello Package browser, that focuses attention on the project 
... I'm not sure that iceberg should be this project-centric browser, 
because the "Metacello project browser" needs to support non-git 
projects as well ... at least I support both in tODE --- and that is 
probably beyond the scope of Iceberg, but necessary none-the-less.

Dale

**Comment by npasserini** [comment]
This was fixed in https://github.com/npasserini/iceberg/commit/ca1790a37de75e6ed204737697e880d4339bd6d5
