### ISSUE TITLE
Cannot switch branch from UI with the IceLibgitLocalRepository backend

### ISSUE THREAD

**Issue by pavel-krivanek** [npasserini/iceberg#249]
With the backend set to IceLibgitLocalRepository if you select the repository and from the context menu select "switch branch", you got DNU:

Instance of IceLibgitLocalRepository did not understand #allBranchNames

**Comment by estebanlm** [comment]
using which branch?

**Comment by pavel-krivanek** [comment]
stable master

**Comment by estebanlm** [comment]
so well... this is fixed upstream. Just stable is still not the latest version.
