### ISSUE TITLE
switching a branch from the list of branches fails

### ISSUE THREAD

**Issue by pavel-krivanek** [npasserini/iceberg#250]
Branch: multi-remotes (loaded by Metacello)

How to reproduce:
- clone repository: https://github.com/tesonep/pharo-talents.git
- select this repository
- go to tab "Branches"
- select branch origin/talentsWithFullHierarchy
- right click for the context menu
- select "Switch to this branch"
- The RedBoxOfDeatch is displayed instead of branches table with the error:
"LGit_GIT_ERROR: Reference 'HEAD' is not a local branch."

**Comment by pavel-krivanek** [comment]
I can switch branches from the context menu on the repositories list.
But if I switch to origin/talentsWithFullHierarchy and then try to "Pull incoming commits" from the context menu of the repositories list, I get the same libGit error

**Comment by pavel-krivanek** [comment]
git status
HEAD detached at 6e04f56
nothing to commit, working directory clean

**Comment by estebanlm** [comment]
fixed on issue #292
