### ISSUE TITLE
DNU MCPostcriptDefinition>>classCategory

### ISSUE THREAD

**Issue by guillep** [npasserini/iceberg#251]
When synchronizing pharo-core (https://github.com/guillep/pharo-core), there is a DNU **MCPostcriptDefinition>>classCategory**. This seems to happen because one of the packages (I'd say **Alien** because I have a **IcePackageChangeSet(Alien)**) contains besides normal method and class definitions a postcript definition (MCPostcriptDefinition instance).

And this postcript definition does not have a class. Thus it fails in:

```
IceClassReference class >> forDefinition: anMCDefinition
	^ anMCDefinition actualClass 
		ifNil: [ IceRemovedClassReference for: anMCDefinition ]
		ifNotNil: [:class | IceSimpleClassReference new targetClass: class ]
```

```
IceRemovedClassReference class >> for: aMCClassDefinition 
	^ self new
		targetClassName: aMCClassDefinition className;
		packageName: aMCClassDefinition classCategory
		yourself
```

**Comment by npasserini** [comment]
I tried to load the pharo-core repository but I get a different error: *addMethod: was sent to nil en rPackageOrganizer*

The problematic package is *VMMaker-interpreter and class is Bitmap. But if we retry it works.
Anyway it does not seem an Iceberg problem

So I can not reproduce this, at least in branch multi-remotes, any suggestions?

**Comment by guillep** [comment]
It doesn't make much sense. If you're trying with pharo-core, you cannot have the error on VMMaker, because that's VM code :). You're probably trying against pharo-vm.

 Try:

github.com/guillep/pharo-core

**Comment by npasserini** [comment]
What I ran is

[ Metacello new
    baseline: 'PharoBootstrapProcess';
    repository: 'github://guillep/PharoBootstrap';
    load ] on: Warning do: #resume.

Which was an adaptation from

[ Metacello new
    baseline: 'Iceberg';
    repository: 'github://npasserini/iceberg';
    load: 'development'.

Metacello new
    baseline: 'PharoBootstrapProcess';
    repository: 'github://guillep/PharoBootstrap';
    load ] on: Warning do: #resume.

#PBBootstrapSpur5032bit asClass new
    gitRepositoryUrl: 'git@github.com:guillep/pharo-core.git'
    location: '.'
    subdirectory: 'src';
    espellBackend: #EPSimulatorBackend asClass for32Bit forBootstrap;
    bootstrap


What should I run?


2017-01-13 10:53 GMT+01:00 Guillermo <notifications@github.com>:

**Comment by npasserini** [comment]
I just tried in a clean image, same result. My script is:

```Metacello new
  baseline: 'Iceberg';
  repository: 'github://npasserini/iceberg:multi-remotes';
  load: #development.

[ Metacello new
    baseline: 'PharoBootstrapProcess';
    repository: 'github://guillep/PharoBootstrap';
    load ] on: Warning do: #resume.
 ```

**Comment by guillep** [comment]
Easier, import

https://github.com/guillep/pharo-core

into iceberg (using git@github.com:guillep/pharo-core.git)

and do a synchronize.

**Comment by npasserini** [comment]
Solved in https://github.com/npasserini/iceberg/commit/09f080714b5371592ab83fc9b476e0d0785c4ac0
Still, it takes ages to synchronize Pharo-core, so I have to continue working on it.
