### ISSUE TITLE
Clone a directory not yet having a code subdirectory ends up in DirectoryDoesNotExistException

### ISSUE THREAD

**Issue by astares** [npasserini/iceberg#257]
Scenario:  Pharo 6.0 Latest update: #60344 on Windows

 - load Iceberg using 

     Metacello new
          baseline: 'Iceberg';
          repository: 'github://npasserini/iceberg:multi-remotes';
          load.

 - go to GitHub and register a new project (initialized only with a README.md) and not yet
    having a subdirectory for the Pharo code
 - open Iceberg and click on "Clone new repository". 
 - enter the git URL:   git@github.com:someUser/NewProject.git and a code subdirectory "src"

This will end up in the "red cross of death" due to an internal DirectoryDoesNotExist exception.

**Comment by estebanlm** [comment]
this should be fixed now.
