### ISSUE TITLE
iceberg broken since Pharo 60356

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#263]
Epicea added the `#isEpiceaCache` on MCRepository. This method is not defined on IceLibgitLocalRepository and so, you get a DNU when you save a package.
The fix is to define
```
IceLibgitLocalRepository>>#isEpiceaCache
	^ false
```

**Comment by estebanlm** [comment]
this is super dirty, I will add it for now, but I will talk with Martin too, to see why this is needed.

**Comment by tinchodias** [comment]
Ooops, today I fix it in epicea.

**Comment by tinchodias** [comment]
I wrongly assumed that every Monticello repository was subclass of MCRepository.

**Comment by tinchodias** [comment]
![the purpose is avoiding these duplicates](https://cloud.githubusercontent.com/assets/3044265/22336963/986b8b28-e3c2-11e6-876a-259ca82aeac5.png)

but each time a MC version is loaded, there was a 'cache' entry, that's manly the noise I wanted to remove with this check.

It's a very secondary feature... it can change it in favor of the anarchic guys of iceberg that do polymorphism without hierarchy, heh.

**Comment by tinchodias** [comment]
Why isn't IceLibgitLocalRepository a subclass of MCRepository?

**Comment by demarey** [comment]
because it is a git repository and not a Monticello repository? ;)

**Comment by dionisiydk** [comment]
2017-01-26 16:52 GMT+01:00 Martín Dias <notifications@github.com>:

> Why isn't IceLibgitLocalRepository a subclass of MCRepository?


Maybe because Iceberg is supposed to replace Monticello at the end of long
long process :)

**Comment by tinchodias** [comment]
But IceRepository shouldn't announce a MCVersionSaved with a new version of a repository that is not a MC repository.

**Comment by tinchodias** [comment]
So, I already did some commits in Epicea removing the use and implementors of isEpiceaCache, but didn't release yet. Now, I think the issue is more on the side of iceberg: Epicea subscribes to MCVersionSaved announcement and receives a MCVersionSaved from Iceberg that doesn't share API with MCRepository.

**Comment by estebanlm** [comment]
maybe... let's wait until @npasserini is more calm and fresh and wait for him to answer why is like that :)

**Comment by demarey** [comment]
Yes but Iceberg now needs to generate a mcz file to save a package. We should update iceberg to avoid this extra step if possible.

----- Mart�n Dias <notifications@github.com> a �crit�:

**Comment by estebanlm** [comment]
AFAIK it does not generates an mcz, it generates a *snapshot*... not the same.

**Comment by demarey** [comment]
You're right Esteban! I wrote too quickly.
In fact, Iceberg creates an MCVersion and to of that also creates a snapshot of the package.
The code is [here](https://github.com/npasserini/iceberg/blob/dev-0.4/Iceberg.package/IceRepository.class/instance/internalSavePackage.withMessage..st#L13).
That's why [an MCVersionSaved is announced](https://github.com/npasserini/iceberg/blob/dev-0.4/Iceberg.package/IceRepository.class/instance/internalSavePackage.withMessage..st#L22) in the IceRepository>>#internalSavePackage:withMessage: method.

**Comment by estebanlm** [comment]
0.4-dev should have been fixed this (still no master, but since this is the development branch). 
@tinchodias please let me know when the testing is not necessary anymore so I can remove the method :)

**Comment by npasserini** [comment]
I am not sure if Iceberg backends should extends from the MCRepository or notCurrently it is just inconsistent, because the OSSubprocess backend does and the Libgit backend does not.

I was thinking about refactoring the OSSubprocess backend to avoid inheritance to MCRepository, but I would like to hear your ideas about that. 

Anyway, if it is not inheriting from MCRepository, then we should ensure that it does not get registered in a MCRepositoryGroup, because that will produce inconsistencies.

**Comment by demarey** [comment]
@npasserini If you plan to drop support of gitFileTree backend, do not spend more time on it. There is still a lot to do on git support and refactor gitFileTree backend will not give a real added value.

I think we should better start to use / create higher level abstractions on top of Monticello. For this specific use case, it could be an announcement like NewCommit thrown both by Monticello or Iceberg.

**Comment by tinchodias** [comment]
Hi! isEpiceaCache is not needed anymore in Iceberg since the new release of Epicea integrated into Pharo 6 last week.
