### ISSUE TITLE
Iceberg does not work on mac (external module issue since ages)

### ISSUE THREAD

**Issue by syrel** [npasserini/iceberg#265]
Take Pharo 6
`wget -O - http://get.pharo.org/60+vm | bash`

Install stable iceberg
```
Metacello new
  baseline: 'Iceberg';
  repository: 'github://npasserini/iceberg';
  load.
```

try to load project leads to `libgit2_init` External module not found.

What Pharo + VM is suitable for iceberg?

**Comment by syrel** [comment]
```
MacBook-Pro:Plugins user$ otool -L libgit2.0.dylib 
libgit2.0.dylib:
	@executable_path/Plugins/libgit2.0.dylib (compatibility version 23.0.0, current version 0.23.0)
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 57336.1.9)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1253.0.0)
	@executable_path/Plugins/libssh2.1.dylib (compatibility version 2.0.0, current version 2.1.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

`LGitLibrary uniqueInstance macModuleName "'libgit2.0.dylib'"`

**Comment by jecisc** [comment]
This is a known issue. Esteban should fix it soon.
You can get Iceberg working by renaming the module name "libgit2.dylib" in the method #macModuleName IIRC  
Then you restart your image.

**Comment by estebanlm** [comment]
latest vm version should work (it is libgit2 bindings issue + a problem in old -present in stable- compilation of libgit2)

**Comment by estebanlm** [comment]
... but you need to load the development branch (0.4-dev)

**Comment by syrel** [comment]
confirm works: Latest VM + image + dev-0.4

**Comment by estebanlm** [comment]
@jecisc this is not necessary anymore, I finally added a "library detection" mechanism on libgit2 :)
