### ISSUE TITLE
MCFileTreeStCypressWriter>>#fileNameMapFor: "name" deprecated

### ISSUE THREAD

**Issue by syrel** [npasserini/iceberg#266]
![screen shot 2017-01-30 at 00 35 43](https://cloud.githubusercontent.com/assets/5487042/22409054/347304c4-e684-11e6-8bfa-d4f460a2b7cd.png)

**Comment by estebanlm** [comment]
this is a Metacello error :(

**Comment by estebanlm** [comment]
the workaround for now is just disable the deprecation raise (until metacello gets updated)

**Comment by dalehenrich** [comment]
You know, you guys can provide pull requests to Metacello. I also don't see an issue report against Metacello:(

**Comment by dalehenrich** [comment]
Don't see a filetree issue either...

**Comment by jecisc** [comment]
I though I opened one for this some month ago but my memories are wrong :(

**Comment by dalehenrich** [comment]
@jecisc you opened two issues against Metacello: https://github.com/dalehenrich/metacello-work/issues/424 and https://github.com/dalehenrich/metacello-work/issues/413 and both were resolved pretty quickly... you opened one issue against filetree: https://github.com/dalehenrich/filetree/issues/199 and it is still open --- and that particular looks like a Metacello bug ... MCGitHubRepository is a Metacello class ... If that one is still a problem, please open a bug against Metacello and I'll take a look ...
