### ISSUE TITLE
Cloning git@github.com:repository creates https://github.com/repository origin url

### ISSUE THREAD

**Issue by JurajKubelka** [npasserini/iceberg#267]
Despite the fact that I clone a `git@github.com:repository` repository, the `.git/config` file points to an `https://github.com/repository` origin url. Tested today on `main` and `dev-0.4` branch.

**Comment by estebanlm** [comment]
this is not a bug, current implementation of libgit2 has a bug with ssh access, reason why we are not supporting it in dev-0.4 (probably we will in next version if we find the time to hack into libgit2 library).
