### ISSUE TITLE
Repository not found error make iceberg unusable

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#274]
* OS 

OSX El captain

* Pharo 

60373

* Way to install Iceberg

```
Metacello new
  baseline: 'Iceberg';
  repository: 'github://npasserini/iceberg:dev-0.4';
  load.
```

* What happened 

I wanted to add a repository but instead of selecting the repository I selected the sub directory. I got an error (LGit_GIT_ENOTFOUND). But now at each click or action I try to make with Iceberg I get a debugger with this error. 

* How to reproduce
  - Install Iceberg
  - Clone a repository with a subdirectory on the disk
  - On Iceberg add a local repository
  - Select the subdirectory instead of the directory
  - Add the sub directory on the second input
  - Create

You get an error. Now you will get this error with many actions as:
- Correct the configuration and re-create the repository
- Close Iceberg and open a new one

**Comment by estebanlm** [comment]
this should be fixed now.
