### ISSUE TITLE
enable use of ssh-agent

### ISSUE THREAD

**Issue by estebanlm** [npasserini/iceberg#275]
the use of SSH it is disabled now (only usable ay now is HTTPS), because libgit2 was not working some time ago, but now we need to implement it.

**Comment by jecisc** [comment]
It would be great because if we add a local repo that was cloned in git bash with ssh remote we have problems using Iceberg :)

**Comment by estebanlm** [comment]
it is already working :) 
https://github.com/estebanlm/iceberg/commits/dev-0.4

just some details missing...

**Comment by estebanlm** [comment]
integrated
