### ISSUE TITLE
Cannot install project via Metacello after installing Iceberg

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#279]
In latest Pharo 6 on Windows 7.

I installed Iceberg[dev-0.4]. Then I executed this script:

```
Metacello new
	githubUser: 'LeCoinEnBande' project: 'OOnoz' commitish: 'development' path: 'src';
	baseline: 'OOnoz';
	load
```

I first got an error: `failed connecting agent`. Then I went to the settings to change the ssh key because I do not have the "default" one on windows. (Maybe we could have a wizard asking for them instead on the error)

After I changed the ssh key I get another error: `DirectoryDoesNotExist: Path / 'C:' / 'Users' / 'JeCisC' / 'AppData' / 'Roaming' / 'Pharo' / 'images' / 'Pharo 6.0 (beta)-11' / 'pharo-local' / 'iceberg' / 'LeCoinEnBande' / 'OOnoz' / 'src'`

**Comment by estebanlm** [comment]
side note: I really hate the place pharolauncher put their images. 
now: this is not a problem with iceberg but with the VM (the FilePlugin, actually), that sometimes decides to not answer correctly...

**Comment by estebanlm** [comment]
by the way, this needs to be reported on Pharo :)

**Comment by jecisc** [comment]
Do I need to open it or do you manage it?

**Comment by estebanlm** [comment]
I guess is already there somewhere... is a know problem but I still don't know how to fix it (because it is hard to reproduce) :(
btw: you should retry to load your project... often it works
- having a shorter path is know to help avoiding this problem.
- if you have the debugger, often going back in the stack and retrying will make it work

**Comment by jecisc** [comment]
I tried many time and it always failed. Maybe I was unlucky. (Now it's not hard anymore to reproduce :P)

**Comment by estebanlm** [comment]
well... *I* have problems to reproduce it :)
anyway, did you tried pointing your iceberg repositories to a shorter path? (like e.g. `c:\dev\repo`)
