### ISSUE TITLE
error when switching branch

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#292]
When you try to switch to another branch from the Branches tab (main iceberg panel), you get a red morph because iceberg thows an error saying that `Reference 'HEAD' is not a local branch`.
Closing and reopening Iceberg UI will throw again this error.

**Comment by demarey** [comment]
to reproduce:
- load iceberg:dev-04,
- open iceberg and clone a repository (give iceberg url)
- try to switch to dev-0.4 branch

**Comment by demarey** [comment]
IceLibgitLocalRepository>>#upstream tries to send the message `#upstream` to `repo head` that is  a reference to 'HEAD' and not a reference to a local branch as expected by [git_branch_upstream](https://libgit2.github.com/libgit2/#HEAD/group/branch/git_branch_upstream)

**Comment by demarey** [comment]
maybe we should use `git_branch_lookup`?

**Comment by demarey** [comment]
duplicate of #250

**Comment by demarey** [comment]
In fact, this problem appears because one try to witch to a remote branch, without having a local branch for it in the local repository.
The solution would be to first create the local branch before doing the checkout when one want to switch to a remote branch

**Comment by estebanlm** [comment]
fixed
