### ISSUE TITLE
a deprecated usage of #name in MCFileTreeStCypressWriter>>#fileNameMapFor:

### ISSUE THREAD

**Issue by pavel-krivanek** [npasserini/iceberg#294]
MCFileTreeStCypressWriter>>#fileNameMapFor: contains on the line 42 a deprecated call on #name. Should be asString

**Comment by estebanlm** [comment]
this is not a metacello problem?

**Comment by ThierryGoubier** [comment]
It's a FileTree problem. I'll add an issue.

**Comment by pavel-krivanek** [comment]
ah, sorry, I have seen this deprecation warning in IceMetadatalessStCypressWrite

**Comment by pavel-krivanek** [comment]
solved in Name: SLICE-Issue-19823-exported-source-of-the-package-MonticelloFileTree-Core-in-pharo-core-repository-contains-strange-extension-PavelKrivanek.1
Author: PavelKrivanek
Time: 13 March 2017, 1:09:28.054389 pm
UUID: 4981ea51-fd06-0d00-8993-9cf30b6654c0
Ancestors: 
Dependencies: MonticelloFileTree-Core-PavelKrivanek.150, MonticelloGUI-PavelKrivanek.435

make the two packages dirty by simple formating change and solution of a the deprecated #name usage.

(https://github.com/npasserini/iceberg/issues/294#issuecomment-286076547)
