### ISSUE TITLE
redmorph if code repository is missing at repository creation

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#299]
To reproduce:
- open Iceberg UI
- clone a repo by specifying a right git url but a wrong value for the subdirectory
=> red morph

**Comment by estebanlm** [comment]
that should not happen with my fixes of yesterday (I tested that case explicitly)

**Comment by demarey** [comment]
I tested with the current version of Iceberg. Yes, the error happens.
Once the repository is created, there are no errors anymore in the UI but there was still one at creation time.

**Comment by estebanlm** [comment]
weird... because I tested it, but well... shit may happens ;)

**Comment by estebanlm** [comment]
btw, that commit makes a lot of property noise... using an old image version? (old STON)?

**Comment by demarey** [comment]
I also noticed that. I use:
Pharo 6.0
Latest update: #60449
STON-Core-SvenVanCaekenberghe.82

**Comment by demarey** [comment]
The only real change is https://github.com/demarey/iceberg/blob/2eb9cfe84ea1e2141a0b54a53ee320c40ab1cd18/Iceberg-UI.package/IceRepositoryModel.class/instance/loadedCodeDescription.st

**Comment by estebanlm** [comment]
yeah, I know… I would refactor that test into a 

self validateDirectoryStructureIfError: [ :message | ^ self makeError: message ].

or something like that.

**Comment by estebanlm** [comment]
afaik, this is fixed, isn't?

**Comment by demarey** [comment]
it should. The PR is integrated
