### ISSUE TITLE
Question: is it needed to download a zip when adding a local repo?

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#306]
There is a high chance that this question will lead to nothing but I wonder if it is necessary to download a zip each time we add a local repository already existing on the disk? 
If the repo is big it can take some time and I don't know if this is needed since we already give a git repo.

**Comment by jecisc** [comment]
Because when I add a new repository to any other git's gui outside Pharo, they can fetch all the infos needed without cloning/downloading sources.

**Comment by estebanlm** [comment]
no is not.
if you do: 

```Smalltalk 
Metacello new 
    repository: 'gitlocal://path/to/my/repo';
    baseline: 'MyBaseline';
    load.
```

it will load your locally-based sources. 
Note: /path/to/my/repo/ needs to point to the filetree structure. For example, in this project: https://github.com/estebanlm/worklog, you will need to do this: 

```Smalltalk 
Metacello new 
    repository: 'gitlocal://path/to/worklog/mc';
    baseline: 'Worklog';
    load.
```

**Comment by jecisc** [comment]
What I do is that I download an image from Jenkins with the project inside. Then I install Iceberg and I add my local repo (already present on disk). And after I added the repo I have a progress bar indicating that iceberg is extracting a zip. Is that normal?

**Comment by cdlm** [comment]
Tried the metacello `gitlocal://` thing, got a `self halt` in `IceMetacelloRepositoryAdapter>>canUpgradeTo:`

**Comment by estebanlm** [comment]
oops
someone let it there... I'm removing it right now
