### ISSUE TITLE
Entry Point into libssh2_userauth_publickey_frommemory is not found

### ISSUE THREAD

**Issue by myroslavarm** [npasserini/iceberg#308]
While trying to clone a repository, the following error arises:
Entry Point into libssh2_userauth_publickey_frommemory is not found in the library DLL libssh2-1.dll. How do I fix this issue?

**Comment by estebanlm** [comment]
using linux? I'm working on fix this issue... :)

**Comment by myroslavarm** [comment]
Windows7

**Comment by estebanlm** [comment]
that's weird, but it can be part of same problem (bad libssh2 version).

**Comment by myroslavarm** [comment]
So is there anything I can do now?

**Comment by estebanlm** [comment]
Which version of VM are you using?

**Comment by myroslavarm** [comment]
5.0, and the image version is Pharo-60450

**Comment by estebanlm** [comment]
what is a 5.0 vm?
anyway, download and try latest VM: http://files.pharo.org/get-files/60/pharo-win-latest.zip

**Comment by myroslavarm** [comment]
Same error

**Comment by estebanlm** [comment]
ok, you have to wait then. 
you can use HTTPS instead SSH in the mean time (it should work)

**Comment by myroslavarm** [comment]
It's the same as for SSH: first the error I described above and then when I close the first error window, it says "external module not found".

**Comment by estebanlm** [comment]
latest VM from windows hast to work 

http://files.pharo.org/get-files/60/pharo-win-latest.zip

yes, is same link as before, but VM is different :) 
anyway, I tested it in a clean Windows7 system and it was working... 
however, there is still one problem you may find (I'm working on fixing it), which is that you need to set "user.name" of project before doing commits... but this is not a windows problem but a missing part of Iceberg :P 

Anyway, to workaround the problem: https://help.github.com/articles/setting-your-username-in-git/ 

(I recommend using `--global` option).
