### ISSUE TITLE
Switching branches does not work

### ISSUE THREAD

**Issue by StephanEggermont** [npasserini/iceberg#310]
Linux, 
VM pharo-linux-i386threaded-201703240126-9d28c11
60450
Metacello new 
   baseline: 'Iceberg'; 
   repository: 'github://npasserini/iceberg:dev-0.4'; 
   load 

Open Iceberg
Clone SeasideSt/Seaside
Tried switching branches from master to origin/develop
UI does not update, shows current branch as master
Switching to the Branches tab gives Red Morph,
LGit_GIT_ERROR: Reference 'HEAD' is not a local branch.
Stack trace:

LGitReturnCodeEnum>>handleLGitReturnCode
LGitReference(LGitExternalObject)>>withReturnHandlerDo:
[ self
	withReturnHandlerDo: [ self branch_upstream: upstream local: self ] ] in LGitReference>>upstream
BlockClosure>>on:do:
LGitReference>>upstream
[ :repo | ^ repo head upstream ifNotNil: #name ] in IceLibgitLocalRepository>>upstream
[ | repo |
repo := (LGitRepository on: self location) open.
aBlock value: repo ] in IceLibgitLocalRepository>>withRepoDo:
[ self checkInitialized.
aBlock value ] in LGitGlobal class>>runSequence:
[ activeProcess psValueAt: index put: anObject.
aBlock value ] in LGitActionSequence(DynamicVariable)>>value:during:
BlockClosure>>ensure:
LGitActionSequence(DynamicVariable)>>value:during:
LGitActionSequence class(DynamicVariable class)>>value:during:
LGitGlobal class>>runSequence:
IceLibgitLocalRepository>>withRepoDo:
IceLibgitLocalRepository>>upstream
IceLocalBranch>>upstream
IceLocalBranch>>incomingCommits
IceRepositoryModel>>statusForBranch:
[ :branch :model | model statusForBranch: branch ] in IceRepositoriesBrowser>>addRepositoryBranchesTo:
BlockClosure>>glamourValueWithArgs:
BlockClosure(ProtoObject)>>glamourValue:
GLMFastTablePresentation(GLMTablePresentation)>>column:valueFor:
[ self glamourPresentation
	column: aGlamourColumn
	valueFor:
		(self glamourPresentation isWithElementIndex
			ifTrue:
				[ anElement asGlamorousMultiValue , anInteger asGlamorousMultiValue ]
			ifFalse: [ anElement ]) ] in GLMFastTableDataSource>>valueFor:withIndex:in:
GLMFastTableDataSource(GLMFastListDataSource)>>cacheAt:for:ifAbsentPut:
GLMFastTableDataSource>>valueFor:withIndex:in:
GLMFastTableDataSource>>viewRowMorphForColumn:element:withIndex:
GLMFastTableDataSource>>rowMorphElementsForColumn:element:withIndex:
GLMFastTableDataSource>>rowMorphForColumn:item:withIndex:
GLMFastTableDataSource>>cellColumn:row:
FTTableContainerMorph>>updateExposedRows
FTTableMorph>>resizeAllSubviews
FTTableMorph>>extent:
FTTableMorph(Morph)>>bounds:
FTTableMorph(Morph)>>layoutInBounds:
FTTableMorph(Morph)>>layoutProportionallyIn:
[ :m | m layoutProportionallyIn: newBounds ] in ProportionalLayout>>layout:in:
Array(SequenceableCollection)>>do:
GLMPanelMorph(Morph)>>submorphsDo:
ProportionalLayout>>layout:in:
GLMPanelMorph(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in GLMPanelMorph(Morph)>>computeFullBounds
BlockClosure>>on:do:
GLMPanelMorph(Morph)>>computeFullBounds
GLMPanelMorph(Morph)>>fullBounds
[ :m | 
| subBox |
m visible
	ifTrue: [ subBox := m fullBounds.
		box
			ifNil: [ box := subBox copy ]
			ifNotNil: [ box := box quickMerge: subBox ] ] ] in GLMPanelMorph(Morph)>>submorphBounds
Array(SequenceableCollection)>>do:
GLMPanelMorph(Morph)>>submorphBounds
GLMPanelMorph(Morph)>>privateFullBounds
GLMPanelMorph(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in GLMPanelMorph(Morph)>>computeFullBounds
BlockClosure>>on:do:
GLMPanelMorph(Morph)>>computeFullBounds
GLMPanelMorph(Morph)>>fullBounds
[ :m | 
| subBox |
m visible
	ifTrue: [ subBox := m fullBounds.
		box
			ifNil: [ box := subBox copy ]
			ifNotNil: [ box := box quickMerge: subBox ] ] ] in LazyTabGroupMorph(Morph)>>submorphBounds
Array(SequenceableCollection)>>do:
LazyTabGroupMorph(Morph)>>submorphBounds
LazyTabGroupMorph(Morph)>>privateFullBounds
LazyTabGroupMorph(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in LazyTabGroupMorph(Morph)>>computeFullBounds
BlockClosure>>on:do:
LazyTabGroupMorph(Morph)>>computeFullBounds
LazyTabGroupMorph(Morph)>>fullBounds
[ :m | 
| subBox |
m visible
	ifTrue: [ subBox := m fullBounds.
		box
			ifNil: [ box := subBox copy ]
			ifNotNil: [ box := box quickMerge: subBox ] ] ] in GLMPanelMorph(Morph)>>submorphBounds
Array(SequenceableCollection)>>do:
GLMPanelMorph(Morph)>>submorphBounds
GLMPanelMorph(Morph)>>privateFullBounds
GLMPanelMorph(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in GLMPanelMorph(Morph)>>computeFullBounds
BlockClosure>>on:do:
GLMPanelMorph(Morph)>>computeFullBounds
GLMPanelMorph(Morph)>>fullBounds
[ :m | 
| subBox |
m visible
	ifTrue: [ subBox := m fullBounds.
		box
			ifNil: [ box := subBox copy ]
			ifNotNil: [ box := box quickMerge: subBox ] ] ] in GLMPanelMorph(Morph)>>submorphBounds
Array(SequenceableCollection)>>do:
GLMPanelMorph(Morph)>>submorphBounds
GLMPanelMorph(Morph)>>privateFullBounds
GLMPanelMorph(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in GLMPanelMorph(Morph)>>computeFullBounds
BlockClosure>>on:do:
GLMPanelMorph(Morph)>>computeFullBounds
GLMPanelMorph(Morph)>>fullBounds
[ :m | 
| subBox |
m visible
	ifTrue: [ subBox := m fullBounds.
		box
			ifNil: [ box := subBox copy ]
			ifNotNil: [ box := box quickMerge: subBox ] ] ] in GLMPanelMorph(Morph)>>submorphBounds
Array(SequenceableCollection)>>do:
GLMPanelMorph(Morph)>>submorphBounds
GLMPanelMorph(Morph)>>privateFullBounds
GLMPanelMorph(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in GLMPanelMorph(Morph)>>computeFullBounds
BlockClosure>>on:do:
GLMPanelMorph(Morph)>>computeFullBounds
GLMPanelMorph(Morph)>>fullBounds
[ :m | 
| subBox |
m visible
	ifTrue: [ subBox := m fullBounds.
		box
			ifNil: [ box := subBox copy ]
			ifNotNil: [ box := box quickMerge: subBox ] ] ] in GLMPanelMorph(Morph)>>submorphBounds
Array(SequenceableCollection)>>do:
GLMPanelMorph(Morph)>>submorphBounds
GLMPanelMorph(Morph)>>privateFullBounds
GLMPanelMorph(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in GLMPanelMorph(Morph)>>computeFullBounds
BlockClosure>>on:do:
GLMPanelMorph(Morph)>>computeFullBounds
GLMPanelMorph(Morph)>>fullBounds
[ :m | 
| subBox |
m visible
	ifTrue: [ subBox := m fullBounds.
		box
			ifNil: [ box := subBox copy ]
			ifNotNil: [ box := box quickMerge: subBox ] ] ] in GLMSystemWindow(Morph)>>submorphBounds
Array(SequenceableCollection)>>do:
GLMSystemWindow(Morph)>>submorphBounds
GLMSystemWindow(Morph)>>privateFullBounds
GLMSystemWindow(Morph)>>doLayoutIn:
[ self doLayoutIn: self layoutBounds ] in GLMSystemWindow(Morph)>>computeFullBounds
BlockClosure>>on:do:
GLMSystemWindow(Morph)>>computeFullBounds
GLMSystemWindow(Morph)>>fullBounds
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>handleMouseOver:
MouseEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
BlockClosure>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
GLMSystemWindow(Morph)>>processEvent:using:
MorphicEventDispatcher>>dispatchDefault:with:
MorphicEventDispatcher>>handleMouseOver:
MouseEvent>>sentTo:
[ ^ anEvent sentTo: self ] in MorphicEventDispatcher>>dispatchEvent:with:
BlockClosure>>ensure:
MorphicEventDispatcher>>dispatchEvent:with:
WorldMorph(Morph)>>processEvent:using:
WorldMorph(Morph)>>processEvent:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendMouseEvent:
HandMorph>>handleEvent:
MouseOverHandler>>handleAsMouseOver:
MouseOverHandler>>processMouseOver:
HandMorph>>handleEvent:
HandMorph>>processEventsFromQueue:
HandMorph>>processEvents
[ :h | 
self activeHand: h.
h processEvents.
self activeHand: nil ] in WorldState>>doOneCycleNowFor:
Array(SequenceableCollection)>>do:
WorldState>>handsDo:
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycle
WorldMorph class>>doOneCycle
[ [ WorldMorph doOneCycle.
Processor yield.
false ] whileFalse: [  ] ] in MorphicUIManager>>spawnNewProcess
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess

**Comment by estebanlm** [comment]
in fact what happens is that you need to create a local branch when switching to that branch.
there is a fix incoming (waiting for a PR)...

**Comment by StephanEggermont** [comment]
Yes, that is definitely something where I want my GUI to support me. 

Git has way too many options, not throwing errors and showing broken morphs is the least we need for Pharo 6

**Comment by estebanlm** [comment]
duplicated of issue #292
