### ISSUE TITLE
remove "Fetch all" button from repositories window?

### ISSUE THREAD

**Issue by estebanlm** [npasserini/iceberg#314]
I think is confusing... and dangerous to ask for a complete fetch/load of all active repositories, so I propose to just remove it. 
What do you think?

**Comment by jecisc** [comment]
Load all actives is dangerous but fetch all should be fine no?

**Comment by estebanlm** [comment]
not really (why would you fetch *all* projects you may have there... including pharo itself). 
I don't see the purpose of this to exist, honestly :)

**Comment by jecisc** [comment]
I don't have iceberg right know to check the interface but do we still see the number of incoming/outgoing commits for each projects if we don't fetch all? If yes, I agree, this button can be removed.

**Comment by estebanlm** [comment]
no, you have to fetch one by one, but you have a point there... in anycase, fetch should just "fetch" (no load)

**Comment by jecisc** [comment]
Yes! 

I use a GUI outside Pharo that allow the user to give a timing for an auto fetch. By default is 3min and if you don't want the auto fetch you put the setting to 0min. What do you think of that for the futur?
