### ISSUE TITLE
add "remove package" option

### ISSUE THREAD

**Issue by jecisc** [npasserini/iceberg#317]
I know I can "unload" a package but can I delete a package from a repository? I could not found how. 

I saw this because I have a project MaterialDesignLite that had a package to manage colors. I extracted it it its own project but I still had the package on the repository MaterialDesignLite event if it was not referenced in the baseline. The only way I found to remove this package from this repo was to do it outside Pharo.

**Comment by estebanlm** [comment]
right now, we do not have this possibility... but I think we could offer a "Remove package" functionality...

**Comment by jecisc** [comment]
If you plan to make git usable from Pharo, it is essential IMO.

**Comment by estebanlm** [comment]
done :)

**Comment by eMaringolo** [comment]
I have the same issue with `Pharo6.0 of 13 May 2016 update 60508`

**Comment by estebanlm** [comment]
did you update 0.5.5 ?
