### ISSUE TITLE
Line breaks are removed from the commit message

### ISSUE THREAD

**Issue by Uko** [npasserini/iceberg#319]
When I commit with iceberg, the commit message ends up without any line break

**Comment by estebanlm** [comment]
mmm... a lineEnding problem?

**Comment by Uko** [comment]
May be. I experienced the problem when commiting on Mac

**Comment by cdlm** [comment]
Confirmed; I'm guessing the text editor in Iceberg uses the Squeak/Pharo/classic Mac convention (carriage return), and Iceberg should convert that to unix linefeeds when sending it to git.

BTW the docs suggest that git expects UTF-8 messages with unix line breaks (I'd rather have Iceberg adopt that), but does support other encodings if properly configured…

**Comment by estebanlm** [comment]
fixed
