### ISSUE TITLE
DNU when creating a local repository

### ISSUE THREAD

**Issue by demarey** [npasserini/iceberg#323]
To reproduce, add a local repository pointing to an empty directory.
You will get DNU: #url was sent to nil
In IceReposiotryCreator>>#createRepository, there is:
```smalltalk
(locationToUse exists not or: [ locationToUse hasChildren not ])
		ifTrue: [ 
			backend 
				cloneRepositoryFrom: self remoteToUse 
				branch: self branchName ].
```
This code will fail because there is no remote to use. We declared a local repository ...

**Comment by estebanlm** [comment]
what you did?

**Comment by demarey** [comment]
it's written in the firs port: **To reproduce, add a local repository pointing to an empty directory** on the file system.

**Comment by estebanlm** [comment]
ah, because is just an empty repository (not a git one)?

**Comment by demarey** [comment]
yes, that

**Comment by estebanlm** [comment]
done :)
