### ISSUE TITLE
When creating a new repository which already exists local you should not be required to input a remote URL

### ISSUE THREAD

**Issue by npasserini** [npasserini/iceberg#75]

**Comment by cdlm** [comment]
I'm guessing the current code gets the remote URL by looking for the origin remote.

However, that assumes there _is_ such a remote. For repos that are really local, instead of realizing there is no remote at all, it gets an empty URL and then fails later when trying to check the URL scheme.

**Comment by estebanlm** [comment]
this is already done :P
