### ISSUE TITLE
Review cloneRepository

### ISSUE THREAD

**Issue by npasserini** [npasserini/iceberg#81]
Currently, if you try to clone an scp url, cloneRepository will change the url and convert it into an https url. This is done because of a bug between libgit2/libssh2 which keeps ssh authentication from working and
cloning with https doesn't require credentials. 

Yet, current tests do not use this behavior so it is not clear that it works. Moreover, I tested that ssh does not work with clone, but this implementation suggests that it might work for other commands. "

**Comment by estebanlm** [comment]
fix is integrated
