### ISSUE TITLE
Metacello does not produce a meaningful error when trying to download an inexistent branch

### ISSUE THREAD

**Issue by npasserini** [npasserini/iceberg#9]
Try this:

```
Metacello new
  baseline: 'FileTree';
  repository: 'github://npasserini/pharo-git:unexistent_branch';
  onConflict: [:ex | ex allow];
  load: 'Git'.
```

**Comment by dalehenrich** [comment]
Is this a Metacello bug? Perhaps it should be submitted as a Metacello issue? Or is this an bug with the way Iceberg uses Metacello?

**Comment by npasserini** [comment]
It is clearly an error of the user, which is not Iceberg as a tool but its Baseline at some point. If you make a mistake in a Baseline, you get a somewhat obscure error, which makes not easy to detect the bug. So I think it could be nice to provide a more explicit error, for helping people (including me, je) discover their own errors.

**Comment by dalehenrich** [comment]
Then this *is* a Metacello bug? Do you plan to submit a Metacello bug, or should I?

**Comment by dalehenrich** [comment]
Never mind, I've submitted the issue :(
